blank_issues_enabled: true
contact_links:
  - name: Dokumentation
    url: https://github.com/SolarEdgePS8/SolarEdge_HA_Energy_Controller#dokumentation
    about: Installation, Mapping, Modi und Fehlerdiagnose
